/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ESFMCIALIDAD;

import javax.swing.JOptionPane;
import java.util.Arrays;
/**
 *
 * @author liebe
 */
public class Preguntas extends javax.swing.JFrame {

    /**
     * Creates new form Preguntas
     */
    public Preguntas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public static int resultados[]={0,0,0,0,0};
    public static boolean cambio[]={false,false,false,false,false} ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpreguntas = new javax.swing.JLabel();
        siguiente = new javax.swing.JButton();
        op0 = new javax.swing.JRadioButton();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        op5 = new javax.swing.JRadioButton();
        prueba1 = new javax.swing.JButton();
        prueba2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpreguntas.setText("Presione siguiente para empezar con las preguntas");

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        op0.setText("0");
        op0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op0ActionPerformed(evt);
            }
        });

        op1.setText("1");

        op2.setText("2");

        op3.setText("3");

        op4.setText("4");

        op5.setText("5");

        prueba1.setText("jButton2");
        prueba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prueba1ActionPerformed(evt);
            }
        });

        prueba2.setText("jButton3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tpreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(op0)
                        .addGap(18, 18, 18)
                        .addComponent(op1)
                        .addGap(18, 18, 18)
                        .addComponent(op2)
                        .addGap(18, 18, 18)
                        .addComponent(op3)
                        .addGap(18, 18, 18)
                        .addComponent(op4)
                        .addGap(18, 18, 18)
                        .addComponent(op5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(prueba1)
                        .addGap(18, 18, 18)
                        .addComponent(prueba2)
                        .addGap(64, 64, 64)
                        .addComponent(siguiente)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tpreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op0)
                    .addComponent(op1)
                    .addComponent(op2)
                    .addComponent(op3)
                    .addComponent(op4)
                    .addComponent(op5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prueba1)
                            .addComponent(prueba2))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(siguiente)
                        .addGap(64, 64, 64))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void op0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op0ActionPerformed

    private void prueba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prueba1ActionPerformed
        int k[] = {(op0.isSelected()) ? 1 : 0, (op1.isSelected()) ? 1 : 0
                    ,(op2.isSelected()) ? 1 : 0, (op3.isSelected()) ? 1 : 0 
                    ,(op4.isSelected()) ? 1 : 0, (op5.isSelected()) ? 1 : 0};
                    
        JOptionPane.showMessageDialog(null, k[0]+k[1]+k[2]+k[3]+k[4]+k[5]);
    }//GEN-LAST:event_prueba1ActionPerformed
    public static int a=0;
    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
       int k[] = {(op0.isSelected()) ? 1 : 0, (op1.isSelected()) ? 1 : 0
                    ,(op2.isSelected()) ? 1 : 0, (op3.isSelected()) ? 1 : 0 
                    ,(op4.isSelected()) ? 1 : 0, (op5.isSelected()) ? 1 : 0};
       int kk = k[0]+k[1]+k[2]+k[3]+k[4]+k[5];
       String ab[]={
           "Teoria","Practica",
           "Practica Matematica","Practica Fisica",
           "Teoria Matematica", "Teoria Fisica",
           "Pasion", "ingresos",
           "encontrar un trabjo rapido","tu carrera"};
        if (kk==0 && a==0 ) {
            tpreguntas.setText("Que tanto prefieres " +ab[0]+" sobre "+ab[1]);
            a++;
            //System.out.print(a);
        }
       if (kk==1){
           if(op0.isSelected()==false){
               switch (a) {
               case 1:
                   resultados[a-1] = k[1]+2*k[2]+3*k[3]+4*k[4]+5*k[5]; //guarda el valor de la pregunta 1
                   tpreguntas.setText("Que tanto prefieres " +ab[2*a]+" sobre "+ab[2*a+1]); // 2,3   a=2
                   System.out.println(resultados[a-1]);
                   break;
               case 2:
                   tpreguntas.setText("Que tanto prefieres " +ab[2*a]+" sobre "+ab[2*a+1]); // 4,5   a=3
                   resultados[a-1] = k[1]+2*k[2]+3*k[3]+4*k[4]+5*k[5];
                   System.out.println(resultados[a-1]);
                   break;
               case 3:
                   tpreguntas.setText("Que tanto prefieres " +ab[2*a]+" sobre "+ab[2*a+1]); // 6,7   a=4
                   resultados[a-1] = k[1]+2*k[2]+3*k[3]+4*k[4]+5*k[5];
                   System.out.println(resultados[a-1]);
                   break;
               case 4:
                   tpreguntas.setText("Que tanto prefieres " +ab[2*a]+" sobre "+ab[2*a+1]); // 8, 9   a=5
                   resultados[a-1] = k[1]+2*k[2]+3*k[3]+4*k[4]+5*k[5];
                   System.out.println(resultados[a-1]);
                   break;   
               case 5:
                   resultados[a-1] = k[1]+2*k[2]+3*k[3]+4*k[4]+5*k[5];
               default:
                   Resultados vresuldatos = new Resultados();
                   vresuldatos.setVisible(true);
                   this.setVisible(false);
                   System.out.println(Arrays.toString(resultados));
                   System.out.println(Arrays.toString(cambio));
                   break;
                }
            a++;   
           }else{
               switch (a) {
               case 1:   //pregunta 1 b sobre a 
                   tpreguntas.setText("Que tanto prefieres " +ab[2*(a-1)+1]+" sobre "+ab[2*(a-1)]); // 1,0 a=1
                   cambio[a-1]=true;
                   System.out.println(resultados[a-1]);
                   break;
               case 2:     //pregunta 2 b sobre a
                   tpreguntas.setText("Que tanto prefieres " +ab[2*(a-1)+1]+" sobre "+ab[2*(a-1)]); // 3,2   a=1
                   System.out.println(resultados[a-1]);
                   cambio[a-1]=true;
                   break;
               case 3: //pregunta 3 b sobre a
                   tpreguntas.setText("Que tanto prefieres " +ab[2*(a-1)+1]+" sobre "+ab[2*(a-1)]); // 5,4   a=2
                   System.out.println(resultados[a-1]);
                   cambio[a-1]=true;
                   break;
               case 4:      //pregunta 4 b sobre a
                   tpreguntas.setText("Que tanto prefieres " +ab[2*(a-1)+1]+" sobre "+ab[2*(a-1)]); // 7,6   a=3
                   System.out.println(resultados[a-1]);
                   cambio[a-1]=true;
                   break;
               case 5:      //pregunta 5 b sobre a
                   tpreguntas.setText("Que tanto prefieres " +ab[2*(a-1)+1]+" sobre "+ab[2*(a-1)]); // 9, 8   a=4
                   System.out.println(resultados[a-1]);
                   cambio[a-1]=true;
                   break;
               default:
                   System.out.println(Arrays.toString(resultados));
                   break;
                }
           }   
       }
       op0.setSelected(false);
       op1.setSelected(false);
       op2.setSelected(false);
       op3.setSelected(false);
       op4.setSelected(false);
       op5.setSelected(false);
    }//GEN-LAST:event_siguienteActionPerformed
// 4 3 4 1 2 4 3 4 1 2
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton op0;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    private javax.swing.JRadioButton op5;
    private javax.swing.JButton prueba1;
    private javax.swing.JButton prueba2;
    private javax.swing.JButton siguiente;
    private javax.swing.JLabel tpreguntas;
    // End of variables declaration//GEN-END:variables
}
